[server]
headless = true
port = 8501
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#0086CE"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f0f8ff"
textColor = "#262730"
font = "sans serif"
